### ISSUE TITLE
fatal error: cuda.h: No such file or directory

### ISSUE THREAD

**Issue by fhong-jpg** [jwyang/faster-rcnn.pytorch#827]
1. when i run (sh make.sh) to compile with python2.7.12. It shows:

/home/skipper/anaconda3/envs/faster_rcnn/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:18: fatal error: cuda.h: No such file or directory
 
2.I am using RTX2060, my CUDA version is 10.1 and i changed the .bashrc file, here is the latter section of my .bashrc:

# export PATH="/home/ys/anaconda3/bin:$PATH"  # commented out by conda initialize
# export PATH="/home/skipper/anaconda3/bin:$PATH"  # commented out by conda initialize

#export LD_LIBRARY_PATH=~/.mujoco/mjpro150/bin${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
#export MUJOCO_KEY_PATH=~/.mujoco${MUJOCO_KEY_PATH}

export LD_LIBRARY_PATH=~/.mujoco/mujoco200/bin${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export MUJOCO_KEY_PATH=~/.mujoco${MUJOCO_KEY_PATH}

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/skipper/.mujoco/mujoco200/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/nvidia-418

export PATH=/usr/local/cuda-10.1/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libGLEW.so:/usr/lib/nvidia-418/libGL.so
export PYTHONPATH="/home/skipper/anaconda3/lib/python3.5/site-packages:$PYTHONPATH"

export CUDA_HOME=/usr/local/cuda-10.1
export PATH="/usr/local/cuda/bin:$PATH"
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
#export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64"
#export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/cuda/lib64"

3.I changed the "CUDA_ARCH" in file "make.sh" for my RTX2060:

CUDA_ARCH="-gencode=arch=compute_50,code=sm_50 \
		-gencode=arch=compute_52,code=sm_52 \
		-gencode=arch=compute_60,code=sm_60 \
		-gencode=arch=compute_61,code=sm_61 \
		-gencode=arch=compute_70,code=sm_70 \
		-gencode=arch=compute_75,code=sm_75 \
		-gencode=arch=compute_75,code=compute_75 "
I don't know how to compile the make.sh successfully, please help me.

**Comment by wztdream** [comment]
you need to install cuda manually
If you use ubuntu, it is easy

sudo apt install nvidia-cuda-toolkit
